### ISSUE TITLE
"python test.py", but there is no test.py

### ISSUE THREAD

**Issue by Nikita-Babich** [gjenca/test_yaml_server#1]
https://github.com/gjenca/test_yaml_server/blob/051b10a631841ecf4a9adbbd38686942410f5f4d/test.sh#L17

I don't see test.py in the repo. Is this supposed to be testnew.py ?

**Comment by Nikita-Babich** [comment]
https://github.com/gjenca/test_yaml_server/blob/051b10a631841ecf4a9adbbd38686942410f5f4d/runtests.sh#L72C8-L72C59
As far as i understand this line makes us search for the test from within a folder, but I don't understand at what point the execution jumps to the folder scope.

**Comment by Nikita-Babich** [comment]
Sorry, just missed the line above it and got confused.

cd $TEST
bash test.sh ../$RIESENIE ${OUT2} 2>${ERR} >${OUT}

**Comment by gjenca** [comment]
1) test.py should be a symbolic link to ../testnew.py
2) You are probably unzipping the repository, or cloning the repository
under windows.
3) You should do

git clone https://github.com/gjenca/test_yaml_server.git

under real Linux, or a "Windows emulator" of Linux.

This preserves the symbolic links in the repo.


Dňa st 10. 4. 2024 o 19:57 Nikita Babich ***@***.***>
napísala(a):
